train:
  - _target_: src.metrics.Accuracy
    name: "accuracy"
  - _target_: src.metrics.F1
    name: "f1"
  - _target_: src.metrics.AUC
    name: "auc"
inference:
  - _target_: src.metrics.Accuracy
    name: "accuracy"
  - _target_: src.metrics.F1
    name: "f1"
  - _target_: src.metrics.AUC
    name: "auc"