defaults:
  - model: fau_model
  - metrics: default
  - dataset: video_dataset
  - dataloader: default
  - transforms: default
  - _self_

seed: 0
device: "auto"

optimizer:
  _target_: torch.optim.AdamW
  betas: [0.9, 0.999]
  lr: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

loss:
  _target_: src.loss.cross_entropy.CrossEntropyLoss
  train_dataset: ${dataset.train}
  device: ${device}
  name: "cross_entropy"

trainer:
  # training process
  strategy: "epochs"  # either epochs or steps
  n_epochs: 50
  epoch_len: null  # max steps in epoch (if `null`, do all steps in each epoch)
  n_steps: null
  eval_steps: null
  save_period: 10  # depends on strategy
  device_tensors: ["frame", "target"]
  clear_cache: False
  resume_from: null

  # early stopping
  early_stopping: True
  value_name: "val_cross_entropy"  # name of a loss or a metric to track (part_name)
  patience: 5
  mode: "min"  # min/max of a value
  
  # saving
  save_dir: "output"

logging:
  run_name: "fau_model_pretrain"
  config_path: "logger_config.json"
