instance_transforms:
  frames:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.PILToTensor
      - _target_: torchvision.transforms.v2.Resize
        size: [224, 224]
      - _target_: src.transforms.ToDtype
        dtype: float32
        scale: True
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

augmentations:
  frames:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
        p: 0.5
      - _target_: torchvision.transforms.v2.RandomRotation
        degrees: 15