train:
  _target_: src.dataset.VideoDataset
  data_dir: "data/VCDF" # ["data/FaceForensics", "data/CelebDF"]
  part: "train"
  val_size: 0.2
  shuffle_index: True
  instance_transforms: ${transforms.instance_transforms}
  augmentations: ${transforms.augmentations}

val:
  _target_: src.dataset.VideoDataset
  data_dir: "data/VCDF" # ["data/FaceForensics", "data/CelebDF"]
  part: "val"
  val_size: 0.2
  instance_transforms: ${transforms.instance_transforms}

test:
  _target_: src.dataset.VideoDataset
  data_dir: "data/hwei_part1"
  part: "val"
  val_size: 1.0
  instance_transforms: ${transforms.instance_transforms}
